
POST http://localhost:3000/aptitude
Content-Type: application/json

{
    "standard":"aptitudeEM",
    "subject":"12-16Unit"
}


###
POST http://localhost:3000/aptitude
Content-Type: application/json

{
    "standard":"aptitudeEM",
    "subject":"12-16Unit"
}

###
POST http://localhost:3001/api/aptitude 
Content-Type: application/json

{
    "userId": "b0b6555d-637f-45d4-9f96-3aad3bd54404",
    "selectedTopics":["simplification", "percentage", "rp"],
    "selectedOptions":5,
    "selectedLanguage":"commonAptitudeTM"
}


###
POST http://localhost:3001/api/weekly-test-em
Content-Type: application/json

{
    "userId": "b0b6555d-637f-45d4-9f96-3aad3bd54404",
    "selectedLanguage": "EM"
}



###
# POST http://localhost:3000/api/duplicate-questions 
# Content-Type: application/json

# {
#     "databaseName":"commonAptitudeEM",
#     "collectionName":"allAptitude"
# }

###
POST http://localhost:3000/api/delete-questions
Content-Type: application/json

{
    "databaseName":"commonAptitudeEM",
    "collectionName":"allAptitude",
    "ids":[
    "6686f2bab7f9839d1d8374df",
    "66881513b7f9839d1d56aa5a",
    "66881513b7f9839d1d56aa5c",
    "66881513b7f9839d1d56aa59",
    "6686ee27b7f9839d1d784940",
    "66881513b7f9839d1d56aa5b",
    "6686ee27b7f9839d1d784960",
    "66881782b7f9839d1d5ccf48",
    "66881513b7f9839d1d56aa5d",
    "6686f2bab7f9839d1d8374e0",
    "6686ee27b7f9839d1d784938",
    "6686ee27b7f9839d1d784964",
    "6686f2bab7f9839d1d8374e1",
    "66881513b7f9839d1d56aa58",
    "6686ee27b7f9839d1d784941",
    "6686f2bab7f9839d1d8374db",
    "6686f2bab7f9839d1d8374e2",
    "6686ee27b7f9839d1d784950",
    "66881782b7f9839d1d5ccf3d",
    "66881782b7f9839d1d5ccf4d"  ]
    }


###
POST http://localhost:3000/status/T32449903325/b0b6555d-637f-45d4-9f96-3aad3bd54404

###
POST http://localhost:3000/api/pay 
Content-Type: application/json

{
    "transactionId": "T32449903325",
    "userId": "b0b6555d-637f-45d4-9f96-3aad3bd54404",
    "name": "jeevan",
    "amount": 1,
    "number": "9999999999"
}


###
POST http://localhost:3000/aggregate-aptitude-questions


###
POST http://localhost:3001/copy-aptitude-questions

###
get http://localhost:3001/api/user/b0b6555d-637f-45d4-9f96-3aad3bd54404